import {chromium} from '../.review-tools/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();page.setDefaultTimeout(15000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base='http://localhost:3002', headers={Origin:base,'X-Requested-With':'XMLHttpRequest'};
const today=new Date().toLocaleDateString('en-CA',{timeZone:'Indian/Mauritius'});
const day=n=>new Date(new Date(today+'T00:00:00Z').getTime()+n*86400000).toISOString().slice(0,10);
const post=async(path,data)=>{const r=await context.request.post(base+'/api'+path,{data,headers});assert.equal(r.status(),200,await r.text());return r.json();};
const notifications=async()=>(await (await context.request.get(base+'/api/admin/records/notifications')).json()).items;
try {
 await page.goto(base+'/admin');await page.getByLabel('Work email').fill('admin@example.com');await page.getByLabel('Password',{exact:true}).fill('a-good-test-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('region',{name:'Action required',exact:true}).waitFor();
 const owner=await post('/admin/records/owners',{name:'Alert Test Owner'});
 const createCar=async(model,nextServiceDate)=>post('/admin/records/vehicles',{ownerId:owner.id,slug:'alerts-'+model.toLowerCase()+'-'+Date.now(),brand:'Toyota',model,registrationNumber:'ALERT '+model,year:2026,category:'suv',dailyRate:2000,mileage:10000,nextServiceMileage:20000,nextServiceDate,published:true});
 const car=await createCar('Deadline',day(7));const overdue=await createCar('Overdue',day(-1));const assigned=await createCar('Assignment',day(90));
 const file=await post('/admin/files',{kind:'document',name:'policy.pdf',contentType:'application/pdf',content:Buffer.from('%PDF-1.4\n%%EOF').toString('base64')});
 const certificate=async(type,expiry)=>post('/admin/records/documents',{vehicleId:car.id,documentType:type,title:type,fileId:file.id,issueDate:day(-365),expiryDate:expiry,compliance:{company:'Insurer',broker:'Broker',policyNumber:'P-ALERT',premium:10000}});
 await certificate('Insurance Certificate',day(-1));await certificate('Fitness Certificate',day(14));await certificate('MVL',day(100));await certificate('Licence',day(100));
 await post('/admin/records/assignments',{vehicleId:assigned.id,assignedTo:'Custodian',assignmentType:'Staff',startDate:today,expectedReturnDate:day(1),mileageOut:10000,reason:'Test return'});
 await page.getByRole('button',{name:'Refresh alerts',exact:true}).click();
 const center=page.getByRole('region',{name:'Action required',exact:true});
 await center.getByRole('heading',{name:'Insurance expired',exact:true}).waitFor();
 await center.getByRole('heading',{name:'Service overdue',exact:true}).waitFor();
 await center.getByRole('heading',{name:'Service approaching',exact:true}).waitFor();
 await page.screenshot({path:'.review-tools/alerts-desktop.png',fullPage:true});
 console.log('PASS dashboard shows overdue and advance date/mileage actions with priority and registration');
 await page.getByRole('button',{name:/Operational alerts:/}).click();
 let drawer=page.getByRole('dialog',{name:'Operational alerts'});
 await drawer.getByRole('button',{name:'Mark all seen',exact:true}).click();
 await drawer.getByText('Seen · action still required',{exact:true}).first().waitFor();
 assert.ok((await notifications()).filter(n=>n.requiresAction).every(n=>n.read));
 await drawer.getByRole('button',{name:'Close alerts'}).click();
 await page.reload();await page.getByRole('region',{name:'Action required',exact:true}).getByRole('heading',{name:'Insurance expired',exact:true}).waitFor();
 console.log('PASS seen actions and notification badge remain after reload until resolved');
 await page.getByRole('button',{name:/Operational alerts:/}).click();drawer=page.getByRole('dialog',{name:'Operational alerts'});
 await drawer.locator('article').filter({has:page.getByRole('heading',{name:'Insurance expired',exact:true})}).getByRole('link',{name:'Review / renew certificate'}).click();
 await page.getByRole('region',{name:'Vehicle setup checklist'}).waitFor();assert.equal(await page.getByRole('heading',{name:'Toyota Deadline (2026)',exact:true}).count(),1);await page.getByRole('button',{name:'Close vehicle profile'}).click();
 console.log('PASS alert opens the exact car profile rather than a broken notification route');
 await certificate('Insurance Certificate',day(365));
 await post('/admin/records/maintenance',{vehicleId:overdue.id,serviceType:'Routine Service',date:today,mileage:10000,garage:'Test Garage',description:'Completed service',nextServiceMileage:30000,nextServiceDate:day(180)});
 await page.goto(base+'/admin');await page.getByRole('region',{name:'Action required',exact:true}).waitFor();
 await page.getByRole('button',{name:'Refresh alerts',exact:true}).click();
 await page.getByRole('heading',{name:'Insurance expired',exact:true}).waitFor({state:'hidden'});await page.getByRole('heading',{name:'Service overdue',exact:true}).waitFor({state:'hidden'});
 const current=await notifications();assert.ok(!current.some(n=>n.vehicleId===car.id && n.title==='Insurance expired'));assert.ok(!current.some(n=>n.vehicleId===overdue.id && n.type==='service_due'));
 console.log('PASS renewal and service completion automatically clear resolved actions, keeping history');
 await page.goto(base+'/admin/settings');const notice=page.getByLabel('Service advance notice (days)',{exact:false});await notice.fill('5');await page.getByRole('button',{name:'Save All System Parameters'}).click();await page.getByText('Fleet operations settings updated and persisted successfully.').waitFor();assert.ok(!(await notifications()).some(n=>n.vehicleId===car.id && n.type==='service_due'));
 console.log('PASS saved reminder-window setting changes alert thresholds');
 await page.goto(base+'/admin');await page.getByRole('region',{name:'Action required',exact:true}).waitFor();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:/Operational alerts:/}).click();await page.screenshot({path:'.review-tools/alerts-mobile.png',fullPage:true});assert.equal(errors.length,0,errors.join('\n'));console.log('PASS mobile alert panel renders without runtime errors');
} catch(e) {await page.screenshot({path:'.review-tools/alerts-failure.png',fullPage:true});throw e;}
finally {await browser.close();}
