import { chromium } from '../.review-tools/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const base = 'http://localhost:3009';
const errors = []; page.on('pageerror', e => errors.push(e.message));
const post = async (path, data) => {
  const r = await context.request.post(base + '/api' + path, { data, headers: { Origin: base, 'X-Requested-With': 'XMLHttpRequest' } });
  assert.equal(r.status(), 200, await r.text()); return r.json();
};
try {
  await page.goto(base + '/admin');
  await page.getByLabel('Work email').fill('admin@example.com');
  await page.getByLabel('Password', { exact: true }).fill('a-good-test-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('region', { name: 'Action required', exact: true }).waitFor();
  const owner = await post('/admin/records/owners', { name: 'Job card owner' });
  const car = await post('/admin/records/vehicles', { ownerId: owner.id, slug: 'job-car-' + Date.now(), brand: 'Toyota', model: 'Corolla', registrationNumber: 'JOB ' + Date.now(), year: 2026, category: 'suv', dailyRate: 2000, mileage: 10000, tyreSize: '205/55 R16' });
  await page.goto(base + '/admin/fleet?vehicleId=' + car.id);
  await page.getByRole('button', { name: 'Service job cards', exact: true }).click();
  await page.getByRole('button', { name: 'New service job', exact: true }).click();
  let dialog = page.getByRole('dialog', { name: 'New service job', exact: true });
  await dialog.getByLabel('Garage / workshop').fill('Test Workshop');
  await dialog.getByLabel('Person taking the car').fill('Sam Driver');
  await dialog.getByLabel('Requested work').fill('Oil and brakes');
  await dialog.getByLabel('Reported problems / instructions').fill('<script>window.bad=true</script>');
  await dialog.getByRole('button', { name: 'Save pending job' }).click();
  const region = page.getByRole('region', { name: 'Service job cards', exact: true });
  await region.getByRole('button', { name: 'Complete service job' }).waitFor();
  const [popup] = await Promise.all([page.waitForEvent('popup'), region.getByRole('button', { name: 'Print service job card' }).click()]);
  await popup.waitForLoadState();
  assert.ok((await popup.locator('body').innerText()).includes('205/55 R16'));
  assert.ok((await popup.locator('body').innerText()).includes(car.registrationNumber));
  assert.equal(await popup.evaluate(() => window.bad), undefined);
  await popup.emulateMedia({ media: 'print' });
  await popup.pdf({ path: '.review-tools/service-job-card.pdf', format: 'A4', printBackground: true });
  await popup.close();
  await region.getByRole('button', { name: 'Complete service job' }).click();
  dialog = page.getByRole('dialog', { name: 'Complete service job', exact: true });
  await dialog.getByLabel('Work completed').fill('Changed oil and checked brakes');
  await dialog.getByLabel('Actual service mileage').fill('10100');
  await dialog.getByLabel('Mechanic name').fill('Alex Mechanic');
  await dialog.getByLabel('Person collecting the car').fill('Sam Driver');
  await dialog.getByLabel('Next service mileage (km)', { exact: true }).fill('20100');
  await dialog.locator('input[type=file]').setInputFiles({ name: 'signed-card.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%%EOF') });
  await dialog.getByRole('button', { name: 'Complete and record service' }).click();
  await region.getByText('Paperwork 1', { exact: true }).waitFor();
  const data = await (await context.request.get(base + '/api/admin/data')).json();
  assert.equal(data.maintenance.filter(m => m.vehicleId === car.id).length, 1);
  assert.equal(data.vehicles.find(v => v.id === car.id).nextServiceMileage, 20100);
  assert.equal(data.documents.filter(d => d.vehicleId === car.id).length, 1);
  const file = await context.request.get(base + await region.getByText('Paperwork 1', { exact: true }).getAttribute('href'));
  assert.equal(file.status(), 200);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '.review-tools/service-job-mobile.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log('Service job creation, safe printable PDF, completion, private paperwork and schedule update passed.');
} finally { await browser.close(); }
