import { RentalLocation } from '../types/booking';

export const RENTAL_LOCATIONS: RentalLocation[] = [
  {
    id: 'airport-mru',
    name: 'SSR International Airport (MRU)',
    area: 'South / Airport',
    pickupFee: 0,
    dropoffFee: 0,
    address: 'Terminal 1 Arrivals Hall & Dedicated Car Park P2, Plaine Magnien',
    isPopular: true,
  },
  {
    id: 'grand-baie-hub',
    name: 'Grand Baie / North Coast Hub',
    area: 'North',
    pickupFee: 0,
    dropoffFee: 0,
    address: 'Sunset Boulevard & Coastal Road, Grand Baie',
    isPopular: true,
  },
  {
    id: 'flic-en-flac-hub',
    name: 'Flic-en-Flac / West Coast Hub',
    area: 'West',
    pickupFee: 0,
    dropoffFee: 0,
    address: 'Royal Road, Flic-en-Flac (Near Villa Caroline)',
    isPopular: true,
  },
  {
    id: 'port-louis-hub',
    name: 'Port Louis Harbour & City Center',
    area: 'Central / Capital',
    pickupFee: 0,
    dropoffFee: 0,
    address: 'Caudan Waterfront Marina, Port Louis',
    isPopular: true,
  },
  {
    id: 'belle-mare-east',
    name: 'Belle Mare / East Coast Resorts',
    area: 'East',
    pickupFee: 300,
    dropoffFee: 300,
    address: 'Coastal Highway, Belle Mare (Resort Drop-off Service)',
    isPopular: false,
  },
  {
    id: 'le-morne-southwest',
    name: 'Le Morne Peninsula & Black River',
    area: 'South West',
    pickupFee: 300,
    dropoffFee: 300,
    address: 'Le Morne Village & Hotel Zones, Black River',
    isPopular: false,
  },
  {
    id: 'hotel-delivery-islandwide',
    name: 'Hotel / Villa Direct Delivery (Island-wide)',
    area: 'Island-wide',
    pickupFee: 450,
    dropoffFee: 450,
    address: 'Direct to your hotel concierge or holiday villa across Mauritius',
    isPopular: true,
  },
];
